#!/bin/bash

echo "Hello"

echo "registerCompany (companyCRN, companyName, Location, organisationRole) - designer"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:registerCompany","1234567891","Company1","Palestine","designer"]}'

echo "registerCompany (companyCRN, companyName, Location, organisationRole) - tester"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:registerCompany","1234567891","Company1","Palestine","tester"]}'

echo "registerCompany (companyCRN, companyName, Location, organisationRole) - Manufacturer"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:registerCompany","1234567891","Company1","Palestine","regulator"]}'

echo "registerCompany (companyCRN, companyName, Location, organisationRole) - Manufacturer"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:registerCompany","1234567891","Company1","Palestine","manufacturer"]}'

sleep 5
echo "registerCompany (companyCRN, companyName, Location, organisationRole) - Distributor"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:registerCompany","1234567892","Company2","Palestine","distributor"]}'

sleep 5

echo "addDrug(name, aadharNo)"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:addDrug","medicine1","serial1","02112020","02112022","1234567891"]}'

sleep 5
echo "createPO"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:createPO","1234567892","1234567891","medicine1","2"]}'

sleep 5

echo "createShipment(name, aadharNo, bankTransactionID)"
peer chaincode invoke -o orderer.pharma-network.com:7050 -C pharmachannel -n pharmanet -c'{"Args":["org.pharma-network.pharmanet:createShipment","1234567892","medicine1","serial1","1234567894"]}'
